# -*- coding: utf-8 -*-
"""Cutomer churn prediciton

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lm9iOlAwlYGnNMMQ_364WvnXDLQ2bgKJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = {
    "Tenure_Months":[60,8,48,5,36,12,72,18,3,55],
    "Usage_Frequency":[95,30,85,20,75,40,98,50,15,90],
    "Satisfaction_Score":[5,2,4,1,4,3,5,3,1,5],
    "Complaints":[0,6,1,8,1,4,0,3,10,0],
    "Resolution_Time_Days":[1,10,2,15,3,8,1,6,20,1],
    "Monthly_Charges":[499,999,599,1200,699,899,450,799,1500,550],
    "Contract_Type":[0,1,0,1,0,1,0,1,1,0],
    "Payment_Regularity":[1,0,1,0,1,1,1,1,0,1],
    "Engagement_Score":[90,25,80,15,70,40,95,55,10,92],
    "Support_Rating":[5,2,4,1,4,3,5,3,1,5],
    "Product_Value":[5,2,4,1,4,3,5,3,1,5],
    "Offers_Used":[1,0,1,0,1,0,1,1,0,1],
    "Purchase_Frequency":[15,3,12,1,10,4,20,6,0,18],
    "Churn":[0,1,0,1,0,1,0,0,1,0]
}

df = pd.DataFrame(data)

X = df.drop("Churn", axis=1)
Y = df["Churn"]

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=2
)

# Loading Model

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Training Model

model.fit(
    X_train,
    Y_train
)

# Prediction on Training Data

training_data_prediction = model.predict(X_train)

training_accuracy = accuracy_score(
    Y_train,
    training_data_prediction
)

print("Training Accuracy :", training_accuracy)


# Prediction on Testing Data

test_data_prediction = model.predict(X_test)

testing_accuracy = accuracy_score(
    Y_test,
    test_data_prediction
)

print("Testing Accuracy :", testing_accuracy)

plt.scatter(
    Y_train,
    training_data_prediction
)

plt.xlabel("Actual Churn")
plt.ylabel("Predicted Churn")
plt.title("Actual Churn vs Predicted Churn (Training Data)")

plt.show()

plt.scatter(
    Y_test,
    test_data_prediction
)

plt.xlabel("Actual Churn")
plt.ylabel("Predicted Churn")
plt.title("Actual Churn vs Predicted Churn (Testing Data)")

plt.show()