# -*- coding: utf-8 -*-
"""Loan Price Prediciton

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoHNhNrD_nIbQdedL7gA81rDWRWbr9PA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Creating Dataset

data = {

    "Admission_Status":[1,1,1,0,1,1,0,1,1,1],
    "Course_Type":[1,2,1,3,1,2,3,1,2,1],
    "College_Ranking":[5,4,5,2,5,4,1,5,3,5],
    "Academic_Score":[85,75,90,55,88,70,50,92,65,95],
    "Loan_Amount":[500000,800000,400000,1200000,600000,900000,1500000,450000,1000000,300000],
    "CoApplicant_Income":[60000,50000,80000,30000,75000,45000,25000,90000,40000,100000],
    "CIBIL_Score":[780,720,820,600,790,700,550,850,650,900],
    "Existing_Loans":[0,1,0,3,0,2,4,0,2,0],
    "Collateral":[1,1,1,0,1,1,0,1,0,1],
    "Course_Duration":[4,2,4,3,4,2,4,4,2,4],
    "Future_Job_Prospect":[1,1,1,0,1,1,0,1,1,1],

    # Target
    "Loan_Approved":[1,1,1,0,1,1,0,1,0,1]
}


df = pd.DataFrame(data)


# Input and Output

X = df.drop("Loan_Approved", axis=1)

Y = df["Loan_Approved"]



# Split Data

X_train, X_test, Y_train, Y_test = train_test_split(

    X,
    Y,
    test_size=0.2,
    random_state=2

)

# Loading Model

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)


# Training Model

model.fit(
    X_train,
    Y_train
)



# Prediction on Training Data

training_data_prediction = model.predict(
    X_train
)


training_accuracy = accuracy_score(
    Y_train,
    training_data_prediction
)


print("Training Accuracy :", training_accuracy)



# Prediction on Testing Data

test_data_prediction = model.predict(
    X_test
)


testing_accuracy = accuracy_score(
    Y_test,
    test_data_prediction
)


print("Testing Accuracy :", testing_accuracy)

plt.plot(
    Y_train.values,
    label="Actual"
)

plt.plot(
    training_data_prediction,
    label="Predicted"
)


plt.xlabel("Student")
plt.ylabel("Loan Approval")

plt.title("Training Data - Actual vs Predicted")

plt.legend()

plt.show()

plt.plot(
    Y_test.values,
    label="Actual"
)

plt.plot(
    test_data_prediction,
    label="Predicted"
)


plt.xlabel("Student")
plt.ylabel("Loan Approval")

plt.title("Testing Data - Actual vs Predicted")

plt.legend()

plt.show()