# -*- coding: utf-8 -*-
"""Student mark predicition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByOipv2z9nuESYlU-zTEEdjYot9juTsR
"""

# ==================================
# NEW STUDENT PREDICTION
# ==================================

print("\n===== NEW STUDENT PREDICTION =====")

previous_marks = 80
attendance = 90
study_hours = 5

presentation = "Better"
resource_type = "Mixed"

presentation_encoded = presentation_encoder.transform(
    [presentation]
)[0]

resource_encoded = resource_encoder.transform(
    [resource_type]
)[0]

new_student = np.array([[
    previous_marks,
    attendance,
    study_hours,
    presentation_encoded,
    resource_encoded
]])

predicted_score = model.predict(new_student)

print(
    "Predicted Student Score :",
    round(predicted_score[0],2)
)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

data = {
    "Previous_Marks":[65,70,75,80,85,90,60,55,72,78,
                      82,88,91,67,73,77,84,89,58,62],

    "Attendance":[70,75,80,85,90,95,65,60,78,82,
                  88,92,96,72,76,81,87,93,68,74],

    "Study_Hours":[2,3,4,5,6,7,1,2,3,4,
                   5,6,7,2,3,4,5,6,1,2],

    "Presentation":[
        "Bad","Good","Good","Better","Better",
        "Better","Bad","Bad","Good","Good",
        "Better","Better","Better","Good",
        "Good","Good","Better","Better",
        "Bad","Bad"
    ],

    "Resource_Type":[
        "Notes","YouTube","Books","AI Tools","Mixed",
        "Mixed","Notes","Notes","YouTube","Books",
        "AI Tools","Mixed","Mixed","YouTube",
        "Books","AI Tools","Mixed","Mixed",
        "Notes","Notes"
    ],

    "Final_Score":[
        60,65,72,80,88,
        95,55,50,70,76,
        84,90,97,66,73,
        78,86,92,54,58
    ]
}

df = pd.DataFrame(data)

presentation_encoder = LabelEncoder()
resource_encoder = LabelEncoder()

df["Presentation"] = presentation_encoder.fit_transform(
    df["Presentation"]
)

df["Resource_Type"] = resource_encoder.fit_transform(
    df["Resource_Type"]
)

# ==================================
# FEATURES & TARGET
# ==================================

X = df.drop("Final_Score", axis=1)

y = df["Final_Score"]

# ==================================
# TRAIN TEST SPLIT
# ==================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==================================
# MODEL
# ==================================

model = LinearRegression()

model.fit(X_train, y_train)

# ==================================
# PREDICTION
# ==================================

train_prediction = model.predict(X_train)

test_prediction = model.predict(X_test)

# ==================================
# EVALUATION
# ==================================

print("\n===== TRAINING RESULTS =====")

print(
    "R2 Score :",
    r2_score(y_train, train_prediction)
)

print(
    "mean_absolute_error:",
    mean_absolute_error(y_train, train_prediction)
)

print(
    "mean_squared_error:",
    mean_squared_error(y_train, train_prediction)
)

print("\n===== TESTING RESULTS =====")

print(
    "R2 Score :",
    r2_score(y_test, test_prediction)
)

print(
    "Mean_absolute_error :",
    mean_absolute_error(y_test, test_prediction)
)

print(
    "Mean_squared_error :",
    mean_squared_error(y_test, test_prediction)
)

# ==================================
# ACTUAL VS PREDICTED GRAPH
# ==================================

plt.figure(figsize=(8,5))

plt.scatter(y_test,test_prediction)

plt.xlabel("Actual Score")
plt.ylabel("Predicted Score")

plt.title("Actual Score vs Predicted Score")

plt.grid(True)

plt.show()

# ==================================
# ACTUAL VS PREDICTED GRAPH
# ==================================

plt.figure(figsize=(8,5))

plt.scatter(y_train,train_prediction)

plt.xlabel("Actual Score")
plt.ylabel("Training Predicted Score")

plt.title("Actual Score vs Training Predicted Score")

plt.grid(True)

plt.show()

